export const savedContacts =[
    {
        image:'imgs/user_image_bitmap.svg'
    },
    {
        image:'imgs/user_image_bitmap.svg'
    },
    {
        image:'imgs/user_image_bitmap.svg'
    },
    {
        image:'imgs/user_image_bitmap.svg'
    },
    {
        image:'imgs/user_image_bitmap.svg'
    },
    {
        image:'imgs/user_image_bitmap.svg'
    },
    {
        image:'imgs/user_image_bitmap.svg'
    },
    {
        image:'imgs/user_image_bitmap.svg'
    },
]